//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kira.AlasFx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kira.AlasFx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数中的字符\&quot;{0}\&quot;不是 {1} 进制数的有效字符。.
        /// </summary>
        internal static string AnyRadixConvert_CharacterIsNotValid {
            get {
                return ResourceManager.GetString("AnyRadixConvert_CharacterIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string AnyRadixConvert_Overflow {
            get {
                return ResourceManager.GetString("AnyRadixConvert_Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缓存功能尚未初始化，未找到可用的 ICacheProvider 实现。.
        /// </summary>
        internal static string Caching_CacheNotInitialized {
            get {
                return ResourceManager.GetString("Caching_CacheNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标识为“{0}”的项重复定义.
        /// </summary>
        internal static string ConfigFile_ItemKeyDefineRepeated {
            get {
                return ResourceManager.GetString("ConfigFile_ItemKeyDefineRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称为“{0}”的类型不存在.
        /// </summary>
        internal static string ConfigFile_NameToTypeIsNull {
            get {
                return ResourceManager.GetString("ConfigFile_NameToTypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上下文初始化类型“{0}”不存在.
        /// </summary>
        internal static string DbContextInitializerConfig_InitializerNotExists {
            get {
                return ResourceManager.GetString("DbContextInitializerConfig_InitializerNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件组中的操作类型错误，只能为And或者Or。.
        /// </summary>
        internal static string Filter_GroupOperateError {
            get {
                return ResourceManager.GetString("Filter_GroupOperateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定的属性“{0}”在类型“{1}”中不存在。.
        /// </summary>
        internal static string Filter_RuleFieldInTypeNotFound {
            get {
                return ResourceManager.GetString("Filter_RuleFieldInTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法解析类型“{0}”的构造函数中类型为“{1}”的参数.
        /// </summary>
        internal static string Ioc_CannotResolveService {
            get {
                return ResourceManager.GetString("Ioc_CannotResolveService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kira.AlasFx框架尚未初始化，请先初始化.
        /// </summary>
        internal static string Ioc_FrameworkNotInitialized {
            get {
                return ResourceManager.GetString("Ioc_FrameworkNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型“{0}”的实现类型无法找到.
        /// </summary>
        internal static string Ioc_ImplementationTypeNotFound {
            get {
                return ResourceManager.GetString("Ioc_ImplementationTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型“{0}”中找不到合适参数的构造函数.
        /// </summary>
        internal static string Ioc_NoConstructorMatch {
            get {
                return ResourceManager.GetString("Ioc_NoConstructorMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实现类型不能为“{0}”，因为该类型与注册为“{1}”的其他类型无法区分.
        /// </summary>
        internal static string Ioc_TryAddIndistinguishableTypeToEnumerable {
            get {
                return ResourceManager.GetString("Ioc_TryAddIndistinguishableTypeToEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型“{0}”不是仓储接口“IRepository”的派生类。.
        /// </summary>
        internal static string IocInitializerBase_TypeNotIRepositoryType {
            get {
                return ResourceManager.GetString("IocInitializerBase_TypeNotIRepositoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型“{0}”不是操作单元“IUnitOfWork”的派生类。.
        /// </summary>
        internal static string IocInitializerBase_TypeNotIUnitOfWorkType {
            get {
                return ResourceManager.GetString("IocInitializerBase_TypeNotIUnitOfWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建名称为“{0}”的日志实例时“{1}”返回空实例。.
        /// </summary>
        internal static string Logging_CreateLogInstanceReturnNull {
            get {
                return ResourceManager.GetString("Logging_CreateLogInstanceReturnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapperExtensions.Mapper不能为空，请先设置值.
        /// </summary>
        internal static string Map_MapperIsNull {
            get {
                return ResourceManager.GetString("Map_MapperIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前Http上下文中不存在Request有效范围的Mef部件容器。.
        /// </summary>
        internal static string Mef_HttpContextItems_NotFoundRequestContainer {
            get {
                return ResourceManager.GetString("Mef_HttpContextItems_NotFoundRequestContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定对象中不存在名称为“{0}”的属性。.
        /// </summary>
        internal static string ObjectExtensions_PropertyNameNotExistsInType {
            get {
                return ResourceManager.GetString("ObjectExtensions_PropertyNameNotExistsInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数“{0}”的值必须在“{1}”与“{2}”之间。.
        /// </summary>
        internal static string ParameterCheck_Between {
            get {
                return ResourceManager.GetString("ParameterCheck_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数“{0}”的值必须在“{1}”与“{2}”之间，且不能等于“{3}”。.
        /// </summary>
        internal static string ParameterCheck_BetweenNotEqual {
            get {
                return ResourceManager.GetString("ParameterCheck_BetweenNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定的目录路径“{0}”不存在。.
        /// </summary>
        internal static string ParameterCheck_DirectoryNotExists {
            get {
                return ResourceManager.GetString("ParameterCheck_DirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定的文件路径“{0}”不存在。.
        /// </summary>
        internal static string ParameterCheck_FileNotExists {
            get {
                return ResourceManager.GetString("ParameterCheck_FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 集合“{0}”中不能包含null的项.
        /// </summary>
        internal static string ParameterCheck_NotContainsNull_Collection {
            get {
                return ResourceManager.GetString("ParameterCheck_NotContainsNull_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数“{0}”的值不能为Guid.Empty.
        /// </summary>
        internal static string ParameterCheck_NotEmpty_Guid {
            get {
                return ResourceManager.GetString("ParameterCheck_NotEmpty_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数“{0}”的值必须大于“{1}”。.
        /// </summary>
        internal static string ParameterCheck_NotGreaterThan {
            get {
                return ResourceManager.GetString("ParameterCheck_NotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数“{0}”的值必须大于或等于“{1}”。.
        /// </summary>
        internal static string ParameterCheck_NotGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("ParameterCheck_NotGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数“{0}”的值必须小于“{1}”。.
        /// </summary>
        internal static string ParameterCheck_NotLessThan {
            get {
                return ResourceManager.GetString("ParameterCheck_NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数“{0}”的值必须小于或等于“{1}”。.
        /// </summary>
        internal static string ParameterCheck_NotLessThanOrEqual {
            get {
                return ResourceManager.GetString("ParameterCheck_NotLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数“{0}”不能为空引用。.
        /// </summary>
        internal static string ParameterCheck_NotNull {
            get {
                return ResourceManager.GetString("ParameterCheck_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数“{0}”不能为空引用或空集合。.
        /// </summary>
        internal static string ParameterCheck_NotNullOrEmpty_Collection {
            get {
                return ResourceManager.GetString("ParameterCheck_NotNullOrEmpty_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数“{0}”不能为空引用或空字符串。.
        /// </summary>
        internal static string ParameterCheck_NotNullOrEmpty_String {
            get {
                return ResourceManager.GetString("ParameterCheck_NotNullOrEmpty_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型“{0}”不是实体类型.
        /// </summary>
        internal static string QueryCacheExtensions_TypeNotEntityType {
            get {
                return ResourceManager.GetString("QueryCacheExtensions_TypeNotEntityType", resourceCulture);
            }
        }
    }
}
